name: Uses the Dynamic README reusable worfklow

on: [push]

jobs:
  update-templates:
    permissions:
      contents: write
      pull-requests: write
      pages: write
    uses: thoughtbot/templates/.github/workflows/dynamic-readme.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
